# Imports an artifact with prebuilt NuGet packages and publishes them to a NuGet feed.

name: Publish NuGet Packages

on:
  workflow_call:
    inputs:
      environment:
        description: The environment in which the job is to be executed.
        required: false
        type: string

      nuget_source:
        description: The destination NuGet package source.
        required: true
        type: string

      nupkg_artifact:
        description: The name of the 'nupkg' artifact to import.
        required: true
        type: string
      nupkg_artifact_workflow:
        description: The name of the workflow that generated the 'nupkg' artifact.
        required: false
        type: string

    secrets:
      NUGET_API_KEY:
        required: true

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  main:
    name: Publish

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Import NuGet Packages
        if: inputs.nupkg_artifact_workflow == ''
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.nupkg_artifact }}
          path: ./nupkg

      - name: Import NuGet Packages
        if: inputs.nupkg_artifact_workflow != ''
        uses: dawidd6/action-download-artifact@master
        with:
          workflow_conclusion: success
          workflow: ${{ inputs.nupkg_artifact_workflow }}
          name: ${{ inputs.nupkg_artifact }}
          path: ./nupkg

      - name: Publish to NuGet
        run: >
          dotnet nuget push ./nupkg/*.nupkg
          --api-key ${{ secrets.NUGET_API_KEY }}
          --source ${{ inputs.nuget_source }}
          --skip-duplicate
